name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Update Website
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          ref: ${{ github.head_ref }}
      - run: node build.js

      # - name: Update pages artifact
        # uses: actions/upload-pages-artifact@v3
        # with:
          # path: . # Or whatever is correct for you
      # - name: Deploy to GitHub Pages
        # id: deployment
        # uses: actions/deploy-pages@v4

      - name: Commit new changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          GIT_STATUS=$(git status --porcelain)
          echo $GIT_STATUS
          git add .
          git commit -am "AUTO: Updated site."
          git push
  
